esp8266:
  board: d1_mini

esphome:
  name: opentherm

wifi:
  ssid: Wifi
  password: TollieBollie!@
  domain: .lan

logger:
  baud_rate: 9600

api:
ota:

opentherm:
  id: thermostat

climate:
  - platform: opentherm
    opentherm_id: thermostat
    name: Verwarming
    id: verwarming
    internal: false
    visual:
      temperature_step: 0.5
      min_temperature: 15

sensor:
  - platform: opentherm
    type: boiler_temperature
    opentherm_id: thermostat
    name: Boiler water temperature
    unit_of_measurement: °C
  - platform: opentherm
    type: boiler_return_temperature
    opentherm_id: thermostat
    unit_of_measurement: °C
    name: Boiler water return temperature
  - platform: opentherm
    type: relative_modulation_level
    opentherm_id: thermostat
    unit_of_measurement: "%"
    name: Boiler relative modulation level
  - platform: opentherm
    type: maximum_relative_modulation_level
    opentherm_id: thermostat
    unit_of_measurement: "%"
    name: Boiler maximum relative modulation level setting
  - platform: opentherm
    type: target_water_temperature
    opentherm_id: thermostat
    unit_of_measurement: °C
    name: Boiler target water temperature

switch:
  - platform: opentherm
    opentherm_id: thermostat
    type: boiler_override
    name: Boiler on override

binary_sensor:
  - platform: opentherm
    opentherm_id: thermostat
    type: flame_on
    name: Boiler flame on
  - platform: opentherm
    opentherm_id: thermostat
    type: thermostat_heating_on
    name: Thermostat heating active
