esp8266:
  board: d1_mini

esphome:
  name: opentherm

wifi:
  ssid: Internet
  password: Internet$$
  manual_ip:
    static_ip: 192.168.0.122
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.1

logger:
  baud_rate: 9600

api:
ota:

opentherm:
  id: thermostat


output:
  - platform: opentherm
    opentherm_id: thermostat
    type: heating
    id: heating
  - platform: opentherm
    opentherm_id: thermostat
    type: hot_water
    id: hot_water
  - platform: opentherm
    opentherm_id: thermostat
    type: boiler_target_temperature
    id: boiler_target_temperature

switch:
  - platform: output
    name: Verwarming aan
    output: heating
  - platform: output
    name: Warm water aan
    output: hot_water

number:
  - platform: template
    name: Boiler doel temperatuur
    step: 1
    restore_value: true
    unit_of_measurement: 째C
    min_value: 0.55
    max_value: 85
    optimistic: true
    set_action:
      then:
        - lambda: |-
            return id(boiler_target_temperature).write_state(x);

sensor:
  - platform: opentherm
    type: boiler_temperature
    opentherm_id: thermostat
    name: Boiler water temperature
    unit_of_measurement: 째C
  - platform: opentherm
    type: boiler_return_temperature
    opentherm_id: thermostat
    unit_of_measurement: 째C
    name: Boiler water return temperature
  - platform: opentherm
    type: relative_modulation_level
    unit_of_measurement: "%"
    opentherm_id: thermostat
    name: Boiler relative modulation level
  - platform: opentherm
    type: target_water_temperature
    opentherm_id: thermostat
    unit_of_measurement: 째C
    name: Boiler water target temperature


binary_sensor:
  - platform: opentherm
    type: flame_on
    name: Flame on
    opentherm_id: thermostat