esp8266:
  board: d1_mini

esphome:
  name: opentherm

wifi:
  ssid: Internet
  password: Internet$$
  manual_ip:
    static_ip: 192.168.0.122
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.1

logger:
  baud_rate: 9600

api:
ota:

opentherm:
  id: thermostat


output:
  - platform: opentherm
    opentherm_id: thermostat
    type: heating
    id: heating
  - platform: opentherm
    opentherm_id: thermostat
    type: hot_water
    id: hot_water
  - platform: opentherm
    opentherm_id: thermostat
    type: boiler_target_temperature
    boiler_max_target_temp: 85
    boiler_min_target_temp: 55
    id: boiler_target_temperature


sensor:
  - platform: opentherm
    type: boiler_temperature
    opentherm_id: thermostat
    name: Boiler water temperature
  - platform: opentherm
    type: boiler_return_temperature
    opentherm_id: thermostat
    name: Boiler water return temperature
