esp8266:
  board: d1_mini

esphome:
  name: opentherm

wifi:
  ssid: Internet
  password: Internet$$
  manual_ip:
    static_ip: 192.168.0.122
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.1

logger:
  baud_rate: 9600

api:
ota:

opentherm:
  id: thermostat

climate:
  - platform: opentherm
    opentherm_id: thermostat
    name: Verwarming
    id: verwarming
    internal: false
    visual:
      temperature_step: 0.5